name: double_date
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.7.5
  image_picker: ^1.0.8
  google_fonts: 6.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  gradient_borders: ^1.0.1
  flutter_feed_reaction: ^0.0.6
  syncfusion_flutter_datepicker: 24.2.6
  flutter_time_picker_spinner: ^2.0.0
  video_player: ^2.9.1
  intl_phone_number_input: ^0.7.4
  glassmorphism_ui: ^0.3.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  http_parser: ^4.0.2
  cached_network_image: ^3.4.0
  timeago: ^3.7.0
  shimmer_animation: ^2.1.0+1
  country_code_picker: ^3.0.0
  device_calendar: ^4.3.2
  timezone: ^0.9.4
  skeletonizer: ^1.4.2
  flutter_contacts: ^1.1.9+2
  google_maps_flutter: ^2.6.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  socket_io_client: ^2.0.3+1
  emoji_picker_flutter: ^2.2.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  firebase_auth: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
